### ISSUE TITLE
How to get typescript errors?

### ISSUE THREAD

**Issue by nexxeln** [Avimitin/nvim#49]
Hi, I'm really new to neovim so please forgive me if this is a dumb issue.

I want to get proper typescript autocomplete and errors, so I wanted to add the typescript LSP.

This is my `custom.lua`

![custom.lua](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/4AA614l3Rw.png)

I'm still not getting the autocomplete and typescript errors in `.ts` and `.tsx` files. I would appreciate it if you could tell me what I'm doing wrong and guide me through the process of installing a LSP.

**Comment by Avimitin** [comment]
Oh, in the latest commit I removed the lsp-installer plugin because it is untrusted. So you will need to first install the tsserver yourself, then open the editor.

**Comment by nexxeln** [comment]
Thank you for the quick reply.

I think I have it installed.

**Comment by Avimitin** [comment]
Can you run command :LspInfo and see what's happening？

**Comment by nexxeln** [comment]
![LspInfo](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/WindowsTerminal_4oE1QFNro8.png)

It says its not a command.

**Comment by Avimitin** [comment]
Can you run command :PackerStatus and use / key to find if the nvim-lspconfig plugin is loaded or not

**Comment by nexxeln** [comment]
It isn't loading ![Not loaded](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/WindowsTerminal_Gb2icwYjG0.png)

**Comment by Avimitin** [comment]
I know what's happening, the `.tsx` file is recognized as `typescriptreact` filetype. So `typescript` filetype won't work. However their are some issue still needs to be fixed, please wait.

**Comment by Avimitin** [comment]
So the solution is here: you need to add `{ "typescriptreact", "tsserver" }` into the `lang` field. This is because neovim recognize file with `.tsx` extension as `typescriptreact` filetype. This will lead to a issue that the treesitter plugin don't know what is `typescriptreact`. So I try to alias them in commit https://github.com/Avimitin/nvim/commit/445d79dae8c63e938c3f2eaa1e6d270dfd400dc4. Please sync the fork and pull the latest commit to make thing works.

Oh, btw, please run `:PackerCompile` after you make changes.

**Comment by nexxeln** [comment]
Got it working! Thanks so much

![working](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/WindowsTerminal_rBuLVMVMUC.png)

And thank you for the great config!
