### ISSUE TITLE
Garbled Chinese characters

### ISSUE THREAD

**Issue by Ahacad** [Avimitin/nvim#5]
Hi, did you meet the problem that Chinese characters become a messy in nvim under this config? I guess the below line might fix this problem.

```
vim.opt.fileencodings = 'utf-8'
```

**Comment by Avimitin** [comment]
See the help page `:h fileencodings`, your file mess up because your file have wrong encoding.

![image](https://user-images.githubusercontent.com/30021675/143042826-46221a75-aa0c-46fd-9269-14de429f29d8.png)

I've set encoding with value 'utf-8'. And it works on my machine.

![image](https://user-images.githubusercontent.com/30021675/143043191-308ba1a3-8112-45d3-96f5-03c85cc0d6a9.png)
