### ISSUE TITLE
Issues related with Rust Format

### ISSUE THREAD

**Issue by ocfox** [Avimitin/nvim#9]
Hi,before v3.13.0. I can use `:RustFmt` format code. Now if i use `:RustFmt` it just print origin code in console. I try to add `vim.g.rustfmt_autosave=1` in lua but not effected. I don't know it may be rust.vim plugin moved or other reasons. So how to use rustfmt now.

**Comment by Avimitin** [comment]
I'm still trying to figure it out. It says that the neovim has built-in rustfmt function. But I fail to use that command too. You can import the rust.vim plugins back for now. I will update document after I find the correct usage.

**Comment by Avimitin** [comment]
https://github.com/rust-lang/rust.vim/issues/461#issuecomment-1005313227

**Comment by Avimitin** [comment]
So the current workaround is to use the built-in LSP format function: `vim.lsp.buf.formatting`. It is set to <kbd>space-m</kbd> in [lua/utils.lua#L146](https://github.com/Avimitin/nvim/blob/master/lua/utils.lua#L146). This may be the best workaround since it will call different formatter based on the filetype. It is now working on Rust, Golang. I will manage to integrate it with lua format.

I will replace it with <kbd>gf</kbd> in the future release. This is because I've set most the lsp keymap to start with key <kbd>g</kbd>.

![image](https://user-images.githubusercontent.com/30021675/149309323-2c1e62db-a2fd-429f-b297-5f9a7f67f693.png)

**Comment by Avimitin** [comment]
Format option can be found here: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#formattingOptions

**Comment by ocfox** [comment]
Thanks
